- platform: time_date
  display_options:
     - 'time'
     - 'date'
     - 'date_time'
#- platform: lastfm
#  api_key: !secret lastfm_api
#  users:
#    - x1ade
- platform: plex_recently_added
  token: !secret plex_token
  host: 192.168.34.32
  port: 32400
#- platform: sonarr_upcoming_media
#  api_key: !secret sonarr_api
#  host: 192.168.34.11
#  port: 8989
#  days: 14
#  ssl: false
#  max: 10 
#- platform: radarr_upcoming_media
#  api_key: !secret radarr_api
#  host: 192.168.34.11
#  port: 7878
#  days: 14
#  ssl: false
#  theaters: false
#  max: 10

- platform: history_stats
  name: "Octopus Free Electricity Session Active in Last 24h"
  unique_id: octopus_free_last_24hr
  entity_id: binary_sensor.octopus_energy_a_038dd11d_octoplus_free_electricity_session
  state: "on"
  type: count
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"

#- platform: template
#  unique_id: octopus_free_electricity_recently_active
#  sensors:
#    octopus_free_electricity_recently_active:
#      friendly_name: "Octopus Free Electricity Recently Active"
#      value_template: >
#        {{ states('sensor.octopus_free_electricity_session_active_in_last_24h') | int > 0 }}
